# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLO11 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80 # number of classes


backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [ 32, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [ 64, 3, 2]] # 1-P2/4      out:64
  - [-1, 1, Conv, [128, 3, 2]] # 2-P3/8      out:128
  - [-1, 1, Conv, [256, 3, 2]] # 3-P4/16     out:256
  - [-1, 1, Conv, [384, 3, 2]] # 4-P5/32     out:384

head:
  - [-1, 1, AIFI, [256, 2]]  # 5
  
  - [-1, 1, Conv, [192, 3, 1]] # 6 (P5/32-large)

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 3], 1, Concat, [1]] # cat backbone P4
  - [-1, 1, Conv, [192, 3, 1]] # 9 (P4/16-medium)

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 2], 1, Concat, [1]] # cat backbone P3
  - [-1, 1, Conv, [192, 3, 1]] # 12 (P3/8-small)

  - [[6, 9, 12], 1, Detect, [nc]] # Detect(P3, P4, P5)


