
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: /media/double/Data/datasets/nuScenese/yolo_dataset
train: 
  - train3d
val: 
  - val3d
test:

# Classes
names:
  0: car
  1: truck
  2: trailer
  3: bus
  
